flappybirdv0:
  env_id: FlappyBird-v0
  epsilon_init: 1
  epsilon_min: 0.02
  epsilon_decay: 0.992
  replay_memory_size: 100000
  mini_batch_size: 256
  network_sync_rate: 500
  alpha: 0.0007
  gamma: 0.99
  reward_threshold: 1000